// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMZV6e4pQgvt5DFRZxWymy6xl4OzGa0Iw',
    appId: '1:212088940360:web:e042e361c798e65e02357d',
    messagingSenderId: '212088940360',
    projectId: 'movie-app-9e53d',
    authDomain: 'movie-app-9e53d.firebaseapp.com',
    storageBucket: 'movie-app-9e53d.appspot.com',
    measurementId: 'G-B2Y7X6GFL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXjlE19Ijr9E0LDFrWWCwjMPtCpvt7_U',
    appId: '1:212088940360:android:5a878fddacf6814e02357d',
    messagingSenderId: '212088940360',
    projectId: 'movie-app-9e53d',
    storageBucket: 'movie-app-9e53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmbQWeu1_EghoLYdKgCCqEQ_RqgJRsmw',
    appId: '1:212088940360:ios:98e7680832a89b6802357d',
    messagingSenderId: '212088940360',
    projectId: 'movie-app-9e53d',
    storageBucket: 'movie-app-9e53d.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );
}
